#!/usr/bin/env python3
"""
Build a curated MTD Explorer HostSpecies.csv.

Inputs
------
1. The current HostSpecies.csv.
2. download_report.tsv generated by download_all_hostspecies_orgdb_inputs.sh.
3. Optional reference overrides for TaxIDs whose Ensembl reference is stored
   under a different taxonomic level.

The first six legacy columns are kept in their original order so current MTD
scripts remain compatible until they are migrated to header-based lookups:

    Taxon_ID,MartDatasets,Scientific_name,OrgDb,Common_name,kegg

Reference metadata is appended after those columns.

The script can also validate/update MartDatasets against the official BioMart
dataset catalogs. Existing values are changed only when one unique, verified
replacement is found.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import html
import os
import re
import shutil
import socket
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable, Optional, Sequence


SCRIPT_VERSION = "1.2.0"

LEGACY_COLUMNS = [
    "Taxon_ID",
    "MartDatasets",
    "Scientific_name",
    "OrgDb",
    "Common_name",
    "kegg",
]

REFERENCE_COLUMNS = [
    "Reference_Taxon_ID",
    "Reference_Scientific_name",
    "Ensembl_name",
    "Ensembl_division",
    "Ensembl_release",
    "Assembly",
    "Genome_URL",
    "GTF_URL",
    "Pep_URL",
    "Reference_status",
    "MartDatasets_status",
]

OUTPUT_COLUMNS = LEGACY_COLUMNS + REFERENCE_COLUMNS

REPORT_COLUMNS = [
    "Taxon_ID",
    "Scientific_name",
    "Reference_Taxon_ID",
    "Reference_Scientific_name",
    "download_status",
    "override_used",
    "Ensembl_division",
    "Ensembl_release",
    "Assembly",
    "MartDatasets_old",
    "MartDatasets_verified",
    "MartDatasets_final",
    "MartDatasets_status",
    "Genome_URL",
    "GTF_URL",
    "Pep_URL",
    "row_status",
    "notes",
]

DIVISION_HOSTS = {
    "EnsemblMain": "https://www.ensembl.org",
    # Backward-compatible alias for older generated CSV files.
    "EnsemblVertebrates": "https://www.ensembl.org",
    "EnsemblMetazoa": "https://metazoa.ensembl.org",
    "EnsemblFungi": "https://fungi.ensembl.org",
    "EnsemblPlants": "https://plants.ensembl.org",
    "EnsemblProtists": "https://protists.ensembl.org",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Merge HostSpecies.csv with validated Ensembl reference metadata "
            "and optionally verify MartDatasets against BioMart."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--hostspecies",
        "-i",
        default="HostSpecies.csv",
        help="Current HostSpecies.csv.",
    )
    parser.add_argument(
        "--download-report",
        "-r",
        required=True,
        help="download_report.tsv from the reference downloader.",
    )
    parser.add_argument(
        "--overrides",
        help=(
            "Optional TSV containing reference overrides. Supported columns "
            "include Taxon_ID, Reference_Taxon_ID, "
            "Reference_Scientific_name, Ensembl_name, Ensembl_division, "
            "Ensembl_release, Assembly, GTF_URL and Pep_URL."
        ),
    )
    parser.add_argument(
        "--output",
        "-o",
        default="HostSpecies.curated.csv",
        help="Curated CSV output.",
    )
    parser.add_argument(
        "--report",
        default="HostSpecies.curated_report.tsv",
        help="Audit report output.",
    )
    parser.add_argument(
        "--validate-biomart",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Validate and repair MartDatasets using official BioMart catalogs.",
    )
    parser.add_argument(
        "--strict-biomart",
        action="store_true",
        help="Fail if any MartDatasets value cannot be verified.",
    )
    parser.add_argument(
        "--allow-incomplete",
        action="store_true",
        help="Write rows lacking complete reference metadata.",
    )
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="Replace HostSpecies.csv after creating a timestamped backup.",
    )
    parser.add_argument(
        "--cache-dir",
        default=str(
            Path.home()
            / ".cache"
            / "mtd_explorer"
            / "hostspecies_biomart"
        ),
        help="Cache directory for BioMart registry and dataset catalogs.",
    )
    parser.add_argument(
        "--cache-max-age-days",
        type=int,
        default=7,
        help="Maximum BioMart cache age. Use 0 to refresh.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=90,
        help="Network timeout per request.",
    )
    parser.add_argument(
        "--retries",
        type=int,
        default=5,
        help="Number of attempts for transient network errors.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=SCRIPT_VERSION,
    )
    args = parser.parse_args()

    if args.cache_max_age_days < 0:
        parser.error("--cache-max-age-days cannot be negative")
    if args.timeout < 1:
        parser.error("--timeout must be at least 1")
    if args.retries < 1:
        parser.error("--retries must be at least 1")
    if args.in_place and args.output != "HostSpecies.curated.csv":
        parser.error("--output cannot be combined with --in-place")

    return args


def say(message: str) -> None:
    print(message, flush=True)


def clean(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "").strip())


def norm_name(value: Any) -> str:
    value = clean(value).lower()
    value = re.sub(r"[^a-z0-9]+", " ", value)
    return clean(value)


def read_delimited(
    path: Path,
    delimiter: str,
) -> tuple[list[str], list[dict[str, str]]]:
    if not path.is_file():
        raise RuntimeError(f"Input file not found: {path}")

    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle, delimiter=delimiter)
        fieldnames = list(reader.fieldnames or [])
        rows = [
            {
                str(key): clean(value)
                for key, value in row.items()
                if key is not None
            }
            for row in reader
        ]

    if not fieldnames:
        raise RuntimeError(f"Input file has no header: {path}")

    return fieldnames, rows


def require_columns(
    fieldnames: Sequence[str],
    required: Iterable[str],
    label: str,
) -> None:
    missing = sorted(set(required).difference(fieldnames))
    if missing:
        raise RuntimeError(
            f"{label} is missing required column(s): "
            + ", ".join(missing)
        )


def index_unique(
    rows: Sequence[dict[str, str]],
    key: str,
    label: str,
) -> dict[str, dict[str, str]]:
    indexed: dict[str, dict[str, str]] = {}
    duplicates: set[str] = set()

    for row in rows:
        value = clean(row.get(key))
        if not value:
            continue
        if value in indexed:
            duplicates.add(value)
        indexed[value] = row

    if duplicates:
        raise RuntimeError(
            f"{label} has duplicate {key} value(s): "
            + ", ".join(sorted(duplicates))
        )

    return indexed


def infer_release(row: dict[str, str]) -> str:
    """
    Resolve the release according to the actual download source.

    Main Ensembl may mirror C. elegans, D. melanogaster and S. cerevisiae
    while retaining a GTF filename suffix that corresponds to the concurrent
    Ensembl Genomes release (for example .63.gtf.gz). In those cases the main
    FTP archive release is still the value reported by the main Ensembl
    catalog, such as 116.

    Ensembl Genomes URLs, by contrast, use the division release encoded in the
    GTF filename.
    """
    source = clean(row.get("source"))
    reported_release = clean(row.get("release"))

    if source == "Ensembl" and reported_release:
        return reported_release

    gtf_file = clean(row.get("gtf_file"))
    gtf_url = clean(row.get("gtf_url"))

    for value in (gtf_file, gtf_url):
        match = re.search(r"\.(\d+)\.gtf(?:\.gz)?(?:$|\?)", value)
        if match:
            return match.group(1)

    return reported_release


def pin_release_url(url: str, release: str) -> str:
    url = clean(url)
    if not url or not release:
        return url

    # Main Ensembl:
    #   /pub/current/gtf/... -> /pub/release-116/gtf/...
    url = re.sub(
        r"/pub/current/",
        f"/pub/release-{release}/",
        url,
        count=1,
    )

    # Ensembl Genomes divisions:
    #   /pub/metazoa/current/... -> /pub/metazoa/release-63/...
    url = re.sub(
        r"/pub/(metazoa|fungi|plants|protists)/current/",
        rf"/pub/\1/release-{release}/",
        url,
        count=1,
    )

    return url


def derive_genome_url(
    pep_url: str,
    gtf_file: str,
    assembly: str,
    release: str,
) -> str:
    """
    Construct the Ensembl toplevel DNA URL from validated GTF/PEP metadata.

    Important:
    The numeric suffix in a GTF filename does not always equal the release of
    the FTP directory. Main Ensembl mirrors C. elegans, D. melanogaster and
    S. cerevisiae using GTF filenames ending in ".63.gtf.gz", while those
    files are distributed in the main Ensembl release-116 archive.

    Therefore, remove whichever numeric GTF suffix is actually present instead
    of requiring it to match the directory release.
    """
    pep_url = clean(pep_url)
    gtf_file = clean(gtf_file)
    assembly = clean(assembly)
    release = clean(release)

    if not pep_url or not gtf_file or not assembly or not release:
        return ""

    match = re.match(
        r"^(?P<prefix_and_assembly>.+)\.(?P<gtf_release>\d+)"
        r"\.gtf(?:\.gz)?$",
        gtf_file,
    )
    if not match:
        return ""

    prefix_and_assembly = match.group("prefix_and_assembly")
    expected_assembly_suffix = f".{assembly}"

    if prefix_and_assembly.endswith(expected_assembly_suffix):
        prefix = prefix_and_assembly[: -len(expected_assembly_suffix)]
    else:
        # Prefer removing the exact assembly wherever possible. This fallback
        # is retained for unusual filename normalization by Ensembl.
        assembly_position = prefix_and_assembly.rfind(expected_assembly_suffix)
        if assembly_position >= 0:
            prefix = prefix_and_assembly[:assembly_position]
        else:
            prefix = prefix_and_assembly.rsplit(".", 1)[0]

    if not prefix:
        return ""

    dna_filename = f"{prefix}.{assembly}.dna.toplevel.fa.gz"

    if "/pep/" not in pep_url:
        return ""

    dna_dir = pep_url.rsplit("/pep/", 1)[0] + "/dna/"
    return dna_dir + dna_filename


def cache_fresh(path: Path, max_age_days: int) -> bool:
    if not path.is_file() or path.stat().st_size == 0:
        return False
    if max_age_days == 0:
        return False
    age = time.time() - path.stat().st_mtime
    return age <= max_age_days * 86400


class Fetcher:
    def __init__(
        self,
        cache_dir: Path,
        timeout: int,
        retries: int,
        max_age_days: int,
    ) -> None:
        self.cache_dir = cache_dir
        self.timeout = timeout
        self.retries = retries
        self.max_age_days = max_age_days
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self.user_agent = (
            f"MTD-Explorer-HostSpecies-curator/{SCRIPT_VERSION}"
        )

    def get_text(
        self,
        url: str,
        cache_name: str,
    ) -> str:
        cache_path = self.cache_dir / cache_name

        if cache_fresh(cache_path, self.max_age_days):
            return cache_path.read_text(
                encoding="utf-8",
                errors="replace",
            )

        last_error: Optional[BaseException] = None

        for attempt in range(1, self.retries + 1):
            try:
                request = urllib.request.Request(
                    url,
                    headers={
                        "User-Agent": self.user_agent,
                        "Accept": "*/*",
                    },
                )
                with urllib.request.urlopen(
                    request,
                    timeout=self.timeout,
                ) as response:
                    payload = response.read()

                if not payload:
                    raise RuntimeError("server returned an empty response")

                temporary = cache_path.with_suffix(
                    cache_path.suffix + ".tmp"
                )
                temporary.write_bytes(payload)
                os.replace(temporary, cache_path)

                return payload.decode("utf-8", errors="replace")

            except urllib.error.HTTPError as exc:
                last_error = exc
                if exc.code in {400, 401, 403, 404, 405, 410}:
                    break
                if attempt < self.retries:
                    time.sleep(min(30, 2 ** (attempt - 1)))

            except (
                urllib.error.URLError,
                TimeoutError,
                socket.timeout,
                OSError,
                RuntimeError,
            ) as exc:
                last_error = exc
                if attempt < self.retries:
                    time.sleep(min(30, 2 ** (attempt - 1)))

        if cache_path.is_file() and cache_path.stat().st_size > 0:
            say(
                f"[WARN] BioMart refresh failed; using stale cache: "
                f"{cache_path}"
            )
            return cache_path.read_text(
                encoding="utf-8",
                errors="replace",
            )

        raise RuntimeError(f"Unable to retrieve {url}: {last_error}")


def choose_gene_mart(registry_xml: str) -> str:
    try:
        root = ET.fromstring(registry_xml)
    except ET.ParseError as exc:
        raise RuntimeError(f"Invalid BioMart registry XML: {exc}") from exc

    candidates: list[tuple[int, str]] = []

    for element in root.iter():
        attributes = element.attrib
        name = clean(attributes.get("name"))
        display = clean(attributes.get("displayName"))
        database = clean(attributes.get("database"))
        combined = f"{name} {display} {database}".lower()

        if not name:
            continue

        score = 0
        if "genes" in combined:
            score += 100
        if "ensembl_mart_ensembl" in combined:
            score += 90
        if re.search(r"(metazoa|fungi|plants|protist)_mart", combined):
            score += 80
        if "variation" in combined or "regulation" in combined:
            score -= 200
        if "sequence" in combined:
            score -= 20

        if score > 0:
            candidates.append((score, name))

    if not candidates:
        raise RuntimeError(
            "Could not identify an Ensembl Genes mart in the registry"
        )

    candidates.sort(key=lambda item: (-item[0], item[1]))
    return candidates[0][1]


def parse_biomart_datasets(text: str) -> list[dict[str, str]]:
    datasets: list[dict[str, str]] = []

    for raw_line in text.splitlines():
        fields = raw_line.rstrip("\r\n").split("\t")
        if len(fields) < 3:
            continue

        # Standard response:
        # TableSet <dataset> <description> <version> ...
        if fields[0] == "TableSet" and len(fields) >= 4:
            dataset = clean(fields[1])
            description = clean(html.unescape(fields[2]))
            version = clean(fields[3])
        else:
            # Tolerate compact responses where dataset is the first field.
            dataset = clean(fields[0])
            description = clean(html.unescape(fields[1]))
            version = clean(fields[2])

        if not dataset or "_gene" not in dataset:
            continue

        datasets.append(
            {
                "dataset": dataset,
                "description": description,
                "version": version,
            }
        )

    return datasets


def fetch_biomart_catalogs(
    divisions: Iterable[str],
    fetcher: Fetcher,
) -> tuple[
    dict[str, list[dict[str, str]]],
    dict[str, str],
]:
    catalogs: dict[str, list[dict[str, str]]] = {}
    errors: dict[str, str] = {}

    for division in sorted(set(divisions)):
        host = DIVISION_HOSTS.get(division)
        if not host:
            errors[division] = "unsupported Ensembl division"
            continue

        safe_division = re.sub(r"[^A-Za-z0-9]+", "_", division)
        registry_url = (
            f"{host}/biomart/martservice?"
            + urllib.parse.urlencode({"type": "registry"})
        )

        try:
            registry = fetcher.get_text(
                registry_url,
                f"{safe_division}_registry.xml",
            )
            mart_name = choose_gene_mart(registry)

            dataset_url = (
                f"{host}/biomart/martservice?"
                + urllib.parse.urlencode(
                    {
                        "type": "datasets",
                        "mart": mart_name,
                    }
                )
            )
            dataset_text = fetcher.get_text(
                dataset_url,
                f"{safe_division}_{mart_name}_datasets.tsv",
            )
            catalog = parse_biomart_datasets(dataset_text)

            if not catalog:
                raise RuntimeError(
                    "BioMart returned no gene datasets"
                )

            catalogs[division] = catalog
            say(
                f"[OK] BioMart {division}: "
                f"{len(catalog)} gene dataset(s)"
            )

        except Exception as exc:
            errors[division] = str(exc)
            say(f"[WARN] BioMart {division}: {exc}")

    return catalogs, errors


def choose_dataset(
    current_dataset: str,
    scientific_name: str,
    reference_name: str,
    assembly: str,
    ensembl_name: str,
    catalog: Sequence[dict[str, str]],
) -> tuple[str, str]:
    current_dataset = clean(current_dataset)

    exact_dataset = [
        item
        for item in catalog
        if item["dataset"] == current_dataset
    ]
    if len(exact_dataset) == 1:
        return current_dataset, "VERIFIED_EXISTING"

    target_names = {
        norm_name(scientific_name),
        norm_name(reference_name),
    }
    target_names.discard("")

    candidates: list[tuple[int, dict[str, str]]] = []

    for item in catalog:
        description_norm = norm_name(item["description"])
        version_norm = norm_name(item["version"])
        dataset_norm = norm_name(item["dataset"])
        score = 0

        for target in target_names:
            if description_norm.startswith(target + " genes"):
                score = max(score, 100)
            elif description_norm.startswith(target):
                score = max(score, 90)
            elif target and target in description_norm:
                score = max(score, 65)

        if assembly and norm_name(assembly) in (
            description_norm + " " + version_norm
        ):
            score += 30

        compact_ensembl_name = re.sub(
            r"[^a-z0-9]+",
            "",
            ensembl_name.lower(),
        )
        compact_dataset = re.sub(
            r"[^a-z0-9]+",
            "",
            item["dataset"].lower(),
        )
        if (
            compact_ensembl_name
            and compact_ensembl_name[:12] in compact_dataset
        ):
            score += 10

        if score > 0:
            candidates.append((score, item))

    if not candidates:
        if current_dataset:
            return current_dataset, "UNVERIFIED_PRESERVED"
        return "", "NOT_FOUND"

    candidates.sort(
        key=lambda pair: (
            -pair[0],
            pair[1]["dataset"],
        )
    )
    best_score = candidates[0][0]
    best = [
        item
        for score, item in candidates
        if score == best_score
    ]

    unique_names = sorted(
        {item["dataset"] for item in best}
    )

    if len(unique_names) == 1:
        selected = unique_names[0]
        if selected == current_dataset:
            return selected, "VERIFIED_EXISTING"
        if current_dataset:
            return selected, "REPLACED_WITH_VERIFIED"
        return selected, "FILLED_VERIFIED"

    if current_dataset:
        return current_dataset, "AMBIGUOUS_PRESERVED"
    return "", "AMBIGUOUS"


def read_overrides(
    path: Optional[Path],
) -> dict[str, dict[str, str]]:
    if path is None:
        return {}

    fields, rows = read_delimited(path, "\t")
    require_columns(fields, {"Taxon_ID"}, "override TSV")
    return index_unique(rows, "Taxon_ID", "override TSV")


def overlay(
    base: dict[str, str],
    override: dict[str, str],
) -> dict[str, str]:
    result = dict(base)
    for key, value in override.items():
        value = clean(value)
        if key != "Taxon_ID" and value:
            result[key] = value
    return result


def write_csv(
    path: Path,
    rows: Sequence[dict[str, str]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")

    with temporary.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=OUTPUT_COLUMNS,
            lineterminator="\n",
            extrasaction="ignore",
        )
        writer.writeheader()
        writer.writerows(rows)

    os.replace(temporary, path)


def write_report(
    path: Path,
    rows: Sequence[dict[str, str]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")

    with temporary.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=REPORT_COLUMNS,
            delimiter="\t",
            lineterminator="\n",
            extrasaction="ignore",
        )
        writer.writeheader()
        writer.writerows(rows)

    os.replace(temporary, path)


def backup_file(path: Path) -> Path:
    timestamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = path.with_name(f"{path.name}.bak.{timestamp}")
    shutil.copy2(path, backup)
    return backup


def main() -> int:
    args = parse_args()

    host_path = Path(args.hostspecies).expanduser().resolve()
    report_path = Path(args.download_report).expanduser().resolve()
    override_path = (
        Path(args.overrides).expanduser().resolve()
        if args.overrides
        else None
    )
    output_path = Path(args.output).expanduser().resolve()
    audit_path = Path(args.report).expanduser().resolve()
    cache_dir = Path(args.cache_dir).expanduser().resolve()

    host_fields, host_rows = read_delimited(host_path, ",")
    require_columns(host_fields, LEGACY_COLUMNS, "HostSpecies.csv")
    report_fields, download_rows = read_delimited(report_path, "\t")
    require_columns(
        report_fields,
        {
            "taxid",
            "scientific_name",
            "ensembl_name",
            "division",
            "assembly",
            "release",
            "source",
            "gtf_url",
            "pep_url",
            "gtf_file",
            "status",
        },
        "download report",
    )

    host_by_taxid = index_unique(
        host_rows,
        "Taxon_ID",
        "HostSpecies.csv",
    )
    download_by_taxid = index_unique(
        download_rows,
        "taxid",
        "download report",
    )
    overrides = read_overrides(override_path)

    unknown_overrides = sorted(
        set(overrides).difference(host_by_taxid),
        key=lambda value: int(value) if value.isdigit() else value,
    )
    if unknown_overrides:
        raise RuntimeError(
            "Override TaxID(s) not found in HostSpecies.csv: "
            + ", ".join(unknown_overrides)
        )

    say("============================================================")
    say("MTD Explorer — curated HostSpecies builder")
    say(f"HostSpecies:       {host_path}")
    say(f"Download report:   {report_path}")
    say(f"Rows:              {len(host_rows)}")
    say(f"BioMart validation:{' yes' if args.validate_biomart else ' no'}")
    say("============================================================")

    provisional: list[dict[str, str]] = []
    audit_rows: list[dict[str, str]] = []
    incomplete_taxids: list[str] = []

    for original in host_rows:
        taxid = clean(original["Taxon_ID"])
        download = dict(download_by_taxid.get(taxid, {}))
        override = overrides.get(taxid, {})
        merged = overlay(download, override)

        override_used = "YES" if override else "NO"
        download_status = clean(download.get("status")) or "MISSING"

        reference_taxid = (
            clean(merged.get("Reference_Taxon_ID"))
            or taxid
        )
        reference_name = (
            clean(merged.get("Reference_Scientific_name"))
            or clean(merged.get("scientific_name"))
            or clean(original["Scientific_name"])
        )
        ensembl_name = clean(merged.get("Ensembl_name")) or clean(
            merged.get("ensembl_name")
        )
        source = clean(merged.get("source"))
        source_division = {
            "Ensembl": "EnsemblMain",
            "EnsemblGenomes:metazoa": "EnsemblMetazoa",
            "EnsemblGenomes:fungi": "EnsemblFungi",
            "EnsemblGenomes:plants": "EnsemblPlants",
            "EnsemblGenomes:protists": "EnsemblProtists",
        }.get(source, "")

        division = (
            clean(merged.get("Ensembl_division"))
            or source_division
            or clean(merged.get("division"))
        )

        # The actual file source has priority over the taxonomy division from
        # the REST catalog. Several model organisms are mirrored in main
        # Ensembl even though their taxonomy division is Metazoa or Fungi.
        if source_division:
            division = source_division
        assembly = clean(merged.get("Assembly")) or clean(
            merged.get("assembly")
        )
        release = clean(merged.get("Ensembl_release")) or infer_release(
            merged
        )
        gtf_url = clean(merged.get("GTF_URL")) or clean(
            merged.get("gtf_url")
        )
        pep_url = clean(merged.get("Pep_URL")) or clean(
            merged.get("pep_url")
        )
        gtf_file = clean(merged.get("gtf_file"))

        gtf_url = pin_release_url(gtf_url, release)
        pep_url = pin_release_url(pep_url, release)

        genome_url = clean(merged.get("Genome_URL")) or derive_genome_url(
            pep_url,
            gtf_file or Path(urllib.parse.urlparse(gtf_url).path).name,
            assembly,
            release,
        )
        genome_url = pin_release_url(genome_url, release)

        notes: list[str] = []
        required_values = {
            "Reference_Taxon_ID": reference_taxid,
            "Reference_Scientific_name": reference_name,
            "Ensembl_name": ensembl_name,
            "Ensembl_division": division,
            "Ensembl_release": release,
            "Assembly": assembly,
            "Genome_URL": genome_url,
            "GTF_URL": gtf_url,
            "Pep_URL": pep_url,
        }
        missing = [
            key
            for key, value in required_values.items()
            if not clean(value)
        ]

        if missing:
            reference_status = "INCOMPLETE"
            incomplete_taxids.append(taxid)
            notes.append(
                "missing reference field(s): "
                + ", ".join(missing)
            )
        else:
            reference_status = (
                "COMPLETE_OVERRIDE"
                if override
                else "COMPLETE"
            )

        row = {
            **{
                column: clean(original.get(column))
                for column in LEGACY_COLUMNS
            },
            "Reference_Taxon_ID": reference_taxid,
            "Reference_Scientific_name": reference_name,
            "Ensembl_name": ensembl_name,
            "Ensembl_division": division,
            "Ensembl_release": release,
            "Assembly": assembly,
            "Genome_URL": genome_url,
            "GTF_URL": gtf_url,
            "Pep_URL": pep_url,
            "Reference_status": reference_status,
            "MartDatasets_status": "NOT_CHECKED",
        }

        provisional.append(row)
        audit_rows.append(
            {
                "Taxon_ID": taxid,
                "Scientific_name": clean(original["Scientific_name"]),
                "Reference_Taxon_ID": reference_taxid,
                "Reference_Scientific_name": reference_name,
                "download_status": download_status,
                "override_used": override_used,
                "Ensembl_division": division,
                "Ensembl_release": release,
                "Assembly": assembly,
                "MartDatasets_old": clean(
                    original.get("MartDatasets")
                ),
                "MartDatasets_verified": "",
                "MartDatasets_final": clean(
                    original.get("MartDatasets")
                ),
                "MartDatasets_status": "NOT_CHECKED",
                "Genome_URL": genome_url,
                "GTF_URL": gtf_url,
                "Pep_URL": pep_url,
                "row_status": reference_status,
                "notes": "; ".join(notes),
            }
        )

    biomart_errors: dict[str, str] = {}

    if args.validate_biomart:
        fetcher = Fetcher(
            cache_dir=cache_dir,
            timeout=args.timeout,
            retries=args.retries,
            max_age_days=args.cache_max_age_days,
        )
        catalogs, biomart_errors = fetch_biomart_catalogs(
            (
                row["Ensembl_division"]
                for row in provisional
                if row["Ensembl_division"]
            ),
            fetcher,
        )

        for row, audit in zip(provisional, audit_rows):
            division = row["Ensembl_division"]
            catalog = catalogs.get(division)

            if catalog is None:
                status = "CATALOG_UNAVAILABLE"
                selected = row["MartDatasets"]
            else:
                selected, status = choose_dataset(
                    current_dataset=row["MartDatasets"],
                    scientific_name=row["Scientific_name"],
                    reference_name=row["Reference_Scientific_name"],
                    assembly=row["Assembly"],
                    ensembl_name=row["Ensembl_name"],
                    catalog=catalog,
                )

            old = row["MartDatasets"]
            row["MartDatasets"] = selected
            row["MartDatasets_status"] = status

            audit["MartDatasets_verified"] = (
                selected
                if status
                in {
                    "VERIFIED_EXISTING",
                    "REPLACED_WITH_VERIFIED",
                    "FILLED_VERIFIED",
                }
                else ""
            )
            audit["MartDatasets_final"] = selected
            audit["MartDatasets_status"] = status

            if old != selected:
                note = (
                    f"MartDatasets changed: "
                    f"{old or '<empty>'} -> {selected or '<empty>'}"
                )
                audit["notes"] = "; ".join(
                    filter(None, [audit["notes"], note])
                )

    unresolved_marts = [
        row["Taxon_ID"]
        for row in provisional
        if row["MartDatasets_status"]
        not in {
            "VERIFIED_EXISTING",
            "REPLACED_WITH_VERIFIED",
            "FILLED_VERIFIED",
            "NOT_CHECKED",
        }
    ]

    if incomplete_taxids and not args.allow_incomplete:
        write_report(audit_path, audit_rows)
        raise RuntimeError(
            "Incomplete reference metadata for TaxID(s): "
            + ", ".join(incomplete_taxids)
            + f". Audit report written to {audit_path}. "
            "Add an override or use --allow-incomplete."
        )

    if args.strict_biomart and unresolved_marts:
        write_report(audit_path, audit_rows)
        raise RuntimeError(
            "Unverified MartDatasets for TaxID(s): "
            + ", ".join(unresolved_marts)
            + f". Audit report written to {audit_path}."
        )

    destination = host_path if args.in_place else output_path
    backup: Optional[Path] = None

    if args.in_place:
        backup = backup_file(host_path)

    write_csv(destination, provisional)
    write_report(audit_path, audit_rows)

    reference_complete = sum(
        row["Reference_status"].startswith("COMPLETE")
        for row in provisional
    )
    marts_verified = sum(
        row["MartDatasets_status"]
        in {
            "VERIFIED_EXISTING",
            "REPLACED_WITH_VERIFIED",
            "FILLED_VERIFIED",
        }
        for row in provisional
    )
    marts_changed = sum(
        audit["MartDatasets_old"]
        != audit["MartDatasets_final"]
        for audit in audit_rows
    )

    say("============================================================")
    say(f"Rows written:             {len(provisional)}")
    say(f"References complete:      {reference_complete}")
    say(f"References incomplete:    {len(provisional) - reference_complete}")
    say(f"MartDatasets verified:    {marts_verified}")
    say(f"MartDatasets changed:     {marts_changed}")
    say(f"MartDatasets unresolved:  {len(unresolved_marts)}")
    say(f"Curated CSV:              {destination}")
    say(f"Audit report:             {audit_path}")
    if backup:
        say(f"Backup:                   {backup}")
    if biomart_errors:
        say("[WARN] BioMart catalog errors:")
        for division, error in sorted(biomart_errors.items()):
            say(f"       {division}: {error}")
    say("============================================================")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        say("\n[ERROR] Interrupted by user.")
        raise SystemExit(130)
    except Exception as exc:
        say(f"[ERROR] {exc}")
        raise SystemExit(1)
