#!/usr/bin/env Rscript

# VERSION: 3.0.0
# OUTPUTS: multi-group venn_diagramm.pdf + euler_diagramm.pdf
# DEFAULT: --plot_type both; Euler accepts 2 or more groups

# MTD Explorer
# High-quality Venn and proportional Euler diagrams for HUMAnN
# GO/KEGG functional features.
#
# The group assignments always come from the mandatory samplesheet.
# Optional extended metadata is intentionally not used.
#
# Presence rule (matching DEG_Anno_Plot.R):
# a feature is present in a group when its normalized abundance is
# greater than the selected threshold in at least one sample from that group.

print_help <- function(exit_status = 0L) {
  cat(
"MTD HUMAnN functional-feature overlap Venn + Euler diagrams

Required:
  --input FILE
      HUMAnN *_DEG.csv file generated by DEG_Anno_Plot.R.

  --samplesheet FILE
      MTD samplesheet.csv. Group assignments are always read from this file.

Optional:
  --sample_col COL
      Sample column name or number in samplesheet. Default: 1

  --group_col COL
      Group column name or number in samplesheet. Default: 2

  --feature_col COL
      Functional-feature column in the DEG table. Default: Name

  --feature_type TYPE
      auto, GO, KEGG, or FEATURE. Default: auto

  --presence_threshold NUM
      Feature is present when normalized abundance is greater than this
      value in at least one sample from the group. Default: 0

  --title TEXT
      Custom plot title. Default: inferred from feature type.

  --subtitle TEXT
      Custom subtitle. Default: automatic count summary.

  --output FILE
      Venn PDF. Default: <input_directory>/venn_diagramm.pdf

  --euler_output FILE
      Euler PDF. Default: <input_directory>/euler_diagramm.pdf

  --plot_type TYPE
      both, venn, or euler. Default: both
      Euler accepts two or more groups and uses all set intersections.

  --label_type TYPE
      count, percent, or both. Default: count

  --width NUM
      PDF width in inches. Default: 10

  --height NUM
      PDF height in inches. Default: 8

  --write_summary
      Also write <output_basename>_summary.tsv.

  --write_lists
      Also write one TXT feature list per group plus shared/union lists.

  -v, --version
      Show script version.

  -h, --help
      Show this help.

Example:
  Rscript MTD_humann_feature_overlap_venn.R \\
    --input /path/Nonhost_hmn_DEG/GO/humann_genefamilies_Abundance_go_translated_DEG.csv \\
    --samplesheet /path/samplesheet.csv \\
    --feature_type GO
"
  )
  quit(status = exit_status)
}

parse_args <- function(args) {
  if (any(args %in% c("-v", "--version"))) {
    cat("MTD_humann_feature_overlap_venn_euler.R version 3.0.0\n")
    cat("Generates Venn and multi-group proportional Euler PDF diagrams.\n")
    quit(status = 0L)
  }

  if (length(args) == 0L || any(args %in% c("-h", "--help"))) {
    print_help(0L)
  }

  opt <- list(
    input = NULL,
    samplesheet = NULL,
    sample_col = "1",
    group_col = "2",
    feature_col = "Name",
    feature_type = "auto",
    presence_threshold = 0,
    title = NULL,
    subtitle = NULL,
    output = NULL,
    euler_output = NULL,
    plot_type = "both",
    label_type = "count",
    width = 10,
    height = 8,
    write_summary = FALSE,
    write_lists = FALSE
  )

  value_options <- c(
    "input", "samplesheet", "sample_col", "group_col", "feature_col",
    "feature_type", "presence_threshold", "title", "subtitle", "output",
    "euler_output", "plot_type", "label_type", "width", "height"
  )
  flag_options <- c("write_summary", "write_lists")
  known <- c(value_options, flag_options)

  i <- 1L
  while (i <= length(args)) {
    key <- args[i]

    if (!startsWith(key, "--")) {
      stop("Unexpected argument: ", key, call. = FALSE)
    }

    name <- sub("^--", "", key)
    if (!name %in% known) {
      stop("Unknown option: --", name, call. = FALSE)
    }

    if (name %in% flag_options) {
      opt[[name]] <- TRUE
      i <- i + 1L
      next
    }

    i <- i + 1L
    values <- character()

    while (i <= length(args) && !startsWith(args[i], "--")) {
      values <- c(values, args[i])
      i <- i + 1L
    }

    if (length(values) == 0L) {
      stop("Missing value for --", name, call. = FALSE)
    }

    value <- paste(values, collapse = " ")

    if (name %in% c("presence_threshold", "width", "height")) {
      value <- suppressWarnings(as.numeric(value))
      if (is.na(value)) {
        stop("--", name, " must be numeric.", call. = FALSE)
      }
    }

    opt[[name]] <- value
  }

  for (required in c("input", "samplesheet")) {
    if (is.null(opt[[required]]) || trimws(opt[[required]]) == "") {
      stop("Missing required argument --", required, call. = FALSE)
    }
  }

  if (!file.exists(opt$input)) {
    stop("Input DEG file does not exist: ", opt$input, call. = FALSE)
  }

  if (!file.exists(opt$samplesheet)) {
    stop("Samplesheet does not exist: ", opt$samplesheet, call. = FALSE)
  }

  if (!opt$plot_type %in% c("both", "venn", "euler")) {
    stop("--plot_type must be both, venn, or euler.", call. = FALSE)
  }

  if (!opt$label_type %in% c("count", "percent", "both")) {
    stop("--label_type must be count, percent, or both.", call. = FALSE)
  }

  if (opt$width <= 0 || opt$height <= 0) {
    stop("--width and --height must be greater than zero.", call. = FALSE)
  }

  opt
}

get_column_name <- function(df, specification, label) {
  columns <- colnames(df)

  if (grepl("^[0-9]+$", specification)) {
    index <- as.integer(specification)
    if (index < 1L || index > ncol(df)) {
      stop(label, " column index is out of range: ", specification, call. = FALSE)
    }
    return(columns[index])
  }

  if (!specification %in% columns) {
    stop(
      label, " column was not found: ", specification,
      "\nAvailable columns:\n  ", paste(columns, collapse = ", "),
      call. = FALSE
    )
  }

  specification
}

to_numeric_safe <- function(x) {
  x <- trimws(as.character(x))
  x[x %in% c("", "-", "NA", "NaN", "nan", "NULL", "null")] <- "0"
  out <- suppressWarnings(as.numeric(x))
  out[is.na(out)] <- 0
  out
}

canonical_name <- function(x) {
  tolower(gsub("[^A-Za-z0-9]", "", x))
}

match_normalized_column <- function(sample_name, matrix_columns) {
  candidates <- unique(c(
    paste0(sample_name, ".norm"),
    paste0(gsub("-", ".", sample_name, fixed = TRUE), ".norm"),
    paste0(make.names(sample_name), ".norm")
  ))

  direct_hits <- candidates[candidates %in% matrix_columns]
  if (length(direct_hits) == 1L) {
    return(direct_hits)
  }

  if (length(direct_hits) > 1L) {
    stop(
      "More than one normalized column matched sample '", sample_name, "': ",
      paste(direct_hits, collapse = ", "),
      call. = FALSE
    )
  }

  target <- canonical_name(paste0(sample_name, ".norm"))
  canonical_hits <- matrix_columns[
    canonical_name(matrix_columns) == target
  ]

  if (length(canonical_hits) == 1L) {
    return(canonical_hits)
  }

  if (length(canonical_hits) > 1L) {
    stop(
      "Ambiguous normalized-column match for sample '", sample_name, "': ",
      paste(canonical_hits, collapse = ", "),
      call. = FALSE
    )
  }

  stop(
    "Could not find the normalized column for sample '", sample_name, "'.\n",
    "Expected a column such as: ", paste0(sample_name, ".norm"), "\n",
    "Available .norm columns:\n  ",
    paste(grep("\\.norm$", matrix_columns, value = TRUE), collapse = ", "),
    call. = FALSE
  )
}

sanitize_filename <- function(x) {
  x <- gsub("[[:space:]]+", "_", x)
  x <- gsub("[^A-Za-z0-9_.-]", "_", x)
  x
}

infer_feature_type <- function(requested_type, input_file) {
  requested_type <- toupper(trimws(requested_type))

  if (requested_type != "AUTO") {
    if (!requested_type %in% c("GO", "KEGG", "FEATURE")) {
      stop("--feature_type must be auto, GO, KEGG, or FEATURE.", call. = FALSE)
    }
    return(requested_type)
  }

  filename <- tolower(basename(input_file))

  if (grepl("go_translated", filename, fixed = TRUE)) {
    return("GO")
  }

  if (grepl("kegg_translated", filename, fixed = TRUE)) {
    return("KEGG")
  }

  "FEATURE"
}

feature_labels <- function(feature_type) {
  if (feature_type == "GO") {
    return(list(
      singular = "GO term",
      plural = "GO terms",
      title = "Gene Ontology terms detected by group"
    ))
  }

  if (feature_type == "KEGG") {
    return(list(
      singular = "KEGG feature",
      plural = "KEGG features",
      title = "KEGG functional features detected by group"
    ))
  }

  list(
    singular = "functional feature",
    plural = "functional features",
    title = "Functional features detected by group"
  )
}

write_feature_list <- function(features, file) {
  writeLines(sort(unique(features)), con = file)
}


safe_metric <- function(x, field) {
  tryCatch(
    {
      if (!is.null(x[[field]])) {
        as.numeric(x[[field]])[1]
      } else {
        NA_real_
      }
    },
    error = function(e) NA_real_
  )
}

euler_fill_colors <- function(number_of_sets) {
  base_colors <- c(
    "#E9C9CF",
    "#BFE5B8",
    "#BDD7EE",
    "#F7D9A6",
    "#D8C4E8",
    "#C4E3E8",
    "#E8D7B7"
  )

  rep(base_colors, length.out = number_of_sets)
}

safe_max_metric <- function(x, field) {
  tryCatch(
    {
      values <- as.numeric(x[[field]])
      values <- values[is.finite(values)]

      if (length(values) == 0L) {
        NA_real_
      } else {
        max(abs(values))
      }
    },
    error = function(e) NA_real_
  )
}

make_euler_grob <- function(
    fit,
    quantities_arg,
    number_of_sets
) {
  label_cex <- if (number_of_sets <= 3L) {
    0.95
  } else if (number_of_sets <= 5L) {
    0.78
  } else {
    0.65
  }

  edge_width <- if (number_of_sets <= 4L) 2 else 1.4

  grid::grid.grabExpr({
    euler_plot <- plot(
      fit,
      fills = list(
        fill = euler_fill_colors(number_of_sets),
        alpha = 0.65
      ),
      edges = list(
        col = "black",
        lwd = edge_width
      ),
      labels = list(
        cex = label_cex,
        font = 2
      ),
      quantities = quantities_arg,
      main = NULL
    )

    if (!is.null(euler_plot)) {
      try(grid::grid.draw(euler_plot), silent = TRUE)
    }
  })
}

save_euler_pdf <- function(
    fit,
    output_file,
    width,
    height,
    title,
    subtitle,
    caption,
    label_type,
    number_of_sets
) {
  quantity_cex <- if (number_of_sets <= 3L) {
    1.05
  } else if (number_of_sets <= 5L) {
    0.82
  } else {
    0.65
  }

  if (label_type == "percent") {
    quantities_arg <- list(
      type = "percent",
      cex = quantity_cex,
      font = 2
    )
  } else if (label_type == "both") {
    quantities_arg <- list(
      type = c("counts", "percent"),
      cex = quantity_cex,
      font = 2
    )
  } else {
    quantities_arg <- list(
      type = "counts",
      cex = quantity_cex,
      font = 2
    )
  }

  euler_grob <- make_euler_grob(
    fit = fit,
    quantities_arg = quantities_arg,
    number_of_sets = number_of_sets
  )

  diagram_width <- if (number_of_sets <= 3L) {
    0.88
  } else if (number_of_sets <= 5L) {
    0.92
  } else {
    0.96
  }

  diagram_height <- if (number_of_sets <= 3L) {
    0.70
  } else {
    0.76
  }

  draw_one <- function() {
    grid::grid.newpage()

    grid::pushViewport(
      grid::viewport(
        x = 0.5,
        y = 0.50,
        width = diagram_width,
        height = diagram_height
      )
    )

    grid::grid.draw(euler_grob)
    grid::popViewport()

    grid::grid.text(
      title,
      x = 0.5,
      y = 0.965,
      gp = grid::gpar(
        fontsize = 18,
        fontface = "bold"
      )
    )

    grid::grid.text(
      subtitle,
      x = 0.5,
      y = 0.925,
      gp = grid::gpar(fontsize = 10)
    )

    grid::grid.text(
      caption,
      x = 0.5,
      y = 0.035,
      gp = grid::gpar(
        fontsize = 8,
        col = "grey35"
      )
    )
  }

  dir.create(
    dirname(output_file),
    recursive = TRUE,
    showWarnings = FALSE
  )

  grDevices::pdf(
    output_file,
    width = width,
    height = height,
    bg = "white"
  )

  draw_one()
  grDevices::dev.off()

  message("[OK] Euler PDF generated: ", output_file)
}


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

opt <- parse_args(commandArgs(trailingOnly = TRUE))

required_packages <- c("ggplot2", "ggVennDiagram", "eulerr")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_packages) > 0L) {
  stop(
    "Missing required R package(s): ",
    paste(missing_packages, collapse = ", "),
    "\nActivate the MTD environment and install/repair these packages before running.",
    call. = FALSE
  )
}

deg <- read.csv(
  opt$input,
  header = TRUE,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

samplesheet <- read.csv(
  opt$samplesheet,
  header = TRUE,
  check.names = FALSE,
  stringsAsFactors = FALSE,
  na.strings = c("", "NA")
)

sample_column <- get_column_name(samplesheet, opt$sample_col, "Sample")
group_column <- get_column_name(samplesheet, opt$group_col, "Group")
feature_column <- get_column_name(deg, opt$feature_col, "Feature")

samplesheet[[sample_column]] <- trimws(as.character(samplesheet[[sample_column]]))
samplesheet[[group_column]] <- trimws(as.character(samplesheet[[group_column]]))

valid_samplesheet_rows <- (
  !is.na(samplesheet[[sample_column]]) &
  samplesheet[[sample_column]] != "" &
  !is.na(samplesheet[[group_column]]) &
  samplesheet[[group_column]] != ""
)

samplesheet <- samplesheet[valid_samplesheet_rows, , drop = FALSE]

if (nrow(samplesheet) == 0L) {
  stop("No valid sample/group rows were found in the samplesheet.", call. = FALSE)
}

duplicate_samples <- unique(
  samplesheet[[sample_column]][duplicated(samplesheet[[sample_column]])]
)

if (length(duplicate_samples) > 0L) {
  stop(
    "Duplicated sample names were found in the samplesheet: ",
    paste(duplicate_samples, collapse = ", "),
    call. = FALSE
  )
}

groups <- unique(samplesheet[[group_column]])

if (length(groups) < 2L) {
  stop(
    "At least two groups are required. Groups found: ",
    paste(groups, collapse = ", "),
    call. = FALSE
  )
}

features <- trimws(as.character(deg[[feature_column]]))
valid_features <- !is.na(features) & features != "" & features != "-"
deg <- deg[valid_features, , drop = FALSE]
features <- features[valid_features]

sample_to_norm_column <- vapply(
  samplesheet[[sample_column]],
  match_normalized_column,
  character(1),
  matrix_columns = colnames(deg)
)

if (anyDuplicated(sample_to_norm_column)) {
  duplicated_columns <- unique(
    sample_to_norm_column[duplicated(sample_to_norm_column)]
  )
  stop(
    "Multiple samples matched the same normalized column: ",
    paste(duplicated_columns, collapse = ", "),
    call. = FALSE
  )
}

group_feature_sets <- list()
group_sample_counts <- integer()

for (group_name in groups) {
  group_samples <- samplesheet[[sample_column]][
    samplesheet[[group_column]] == group_name
  ]
  group_columns <- unname(sample_to_norm_column[group_samples])

  abundance <- as.data.frame(
    lapply(deg[, group_columns, drop = FALSE], to_numeric_safe),
    check.names = FALSE
  )

  present <- rowSums(
    abundance > opt$presence_threshold,
    na.rm = TRUE
  ) > 0

  group_feature_sets[[group_name]] <- sort(unique(features[present]))
  group_sample_counts[group_name] <- length(group_samples)
}

empty_groups <- names(group_feature_sets)[
  lengths(group_feature_sets) == 0L
]

if (length(empty_groups) > 0L) {
  warning(
    "No features passed the presence threshold for group(s): ",
    paste(empty_groups, collapse = ", ")
  )
}

feature_type <- infer_feature_type(opt$feature_type, opt$input)
labels <- feature_labels(feature_type)

group_counts <- lengths(group_feature_sets)
union_features <- sort(unique(unlist(group_feature_sets, use.names = FALSE)))
shared_all <- sort(Reduce(intersect, group_feature_sets))

if (is.null(opt$title)) {
  title_text <- labels$title
} else {
  title_text <- opt$title
}

if (is.null(opt$subtitle)) {
  group_summary <- paste0(
    names(group_counts), ": ", as.integer(group_counts)
  )

  shared_label <- if (length(group_feature_sets) == 2L) {
    "Shared"
  } else {
    "Shared by all"
  }

  subtitle_text <- paste(
    c(
      group_summary,
      paste0(shared_label, ": ", length(shared_all)),
      paste0("Union: ", length(union_features))
    ),
    collapse = " | "
  )
} else {
  subtitle_text <- opt$subtitle
}

caption_text <- paste0(
  "Presence was defined as normalized abundance > ",
  format(opt$presence_threshold, scientific = FALSE, trim = TRUE),
  " in at least one sample from the corresponding group. ",
  "Numbers inside regions represent disjoint ",
  labels$singular,
  " counts."
)

if (is.null(opt$output)) {
  output_file <- file.path(dirname(opt$input), "venn_diagramm.pdf")
} else {
  output_file <- opt$output
}

if (is.null(opt$euler_output)) {
  euler_output_file <- file.path(
    dirname(opt$input),
    "euler_diagramm.pdf"
  )
} else {
  euler_output_file <- opt$euler_output
}

if (tolower(tools::file_ext(output_file)) != "pdf") {
  stop("--output must end in .pdf", call. = FALSE)
}

if (tolower(tools::file_ext(euler_output_file)) != "pdf") {
  stop("--euler_output must end in .pdf", call. = FALSE)
}

dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)
dir.create(dirname(euler_output_file), recursive = TRUE, showWarnings = FALSE)

message("============================================================")
message("MTD HUMAnN functional-feature overlap | VERSION 3.0.0 | MULTI-GROUP VENN + EULER")
message("Input DEG table: ", opt$input)
message("Samplesheet: ", opt$samplesheet)
message("Sample column: ", sample_column)
message("Group column: ", group_column)
message("Feature column: ", feature_column)
message("Feature type: ", feature_type)
message("Presence threshold: > ", opt$presence_threshold)
message("Groups: ", paste(groups, collapse = ", "))
message("Plot type: ", opt$plot_type)
message("Venn PDF: ", output_file)
message("Euler PDF: ", euler_output_file)
message("============================================================")

for (group_name in groups) {
  group_samples <- samplesheet[[sample_column]][
    samplesheet[[group_column]] == group_name
  ]

  message(
    "[GROUP] ", group_name,
    " | samples=", length(group_samples),
    " | ", labels$plural, "=", length(group_feature_sets[[group_name]])
  )
  message("        ", paste(group_samples, collapse = ", "))
}

message("[SUMMARY] Shared by all groups: ", length(shared_all))
message("[SUMMARY] Union: ", length(union_features))

if (opt$plot_type %in% c("both", "venn")) {
  message("[PLOT] Generating Venn diagram...")

  plot_object <- suppressMessages({
    ggVennDiagram::ggVennDiagram(
      group_feature_sets,
      label = opt$label_type,
      label_alpha = 0,
      label_geom = "label",
      label_size = 5,
      edge_size = 1.1,
      set_size = 5.2
    ) +
      ggplot2::scale_fill_gradient(
        low = "#FFF8F9",
        high = "#BFE5B8",
        name = paste0("Region\n", labels$singular, "\ncount")
      ) +
      ggplot2::labs(
        title = title_text,
        subtitle = subtitle_text,
        caption = caption_text
      ) +
      ggplot2::scale_x_continuous(
        expand = ggplot2::expansion(mult = c(0.10, 0.08))
      ) +
      ggplot2::scale_y_continuous(
        expand = ggplot2::expansion(mult = c(0.10, 0.10))
      ) +
      ggplot2::coord_fixed(clip = "off") +
      ggplot2::theme_void(base_size = 16) +
      ggplot2::theme(
        plot.title = ggplot2::element_text(
          hjust = 0.5,
          face = "bold",
          size = 22,
          margin = ggplot2::margin(b = 8)
        ),
        plot.subtitle = ggplot2::element_text(
          hjust = 0.5,
          size = 13,
          margin = ggplot2::margin(b = 20)
        ),
        plot.caption = ggplot2::element_text(
          hjust = 0.5,
          size = 10,
          color = "grey35",
          margin = ggplot2::margin(t = 18)
        ),
        legend.position = "right",
        legend.title = ggplot2::element_text(size = 11, face = "bold"),
        legend.text = ggplot2::element_text(size = 10),
        plot.margin = ggplot2::margin(20, 25, 20, 55)
      )
  })

  ggplot2::ggsave(
    filename = output_file,
    plot = plot_object,
    width = opt$width,
    height = opt$height,
    units = "in",
    device = "pdf",
    bg = "white",
    limitsize = FALSE
  )

  message("[OK] PDF generated: ", output_file)

}



if (opt$plot_type %in% c("both", "euler")) {
  number_of_sets <- length(group_feature_sets)

  if (number_of_sets < 2L) {
    stop(
      "Euler output requires at least two groups. Groups found: ",
      paste(names(group_feature_sets), collapse = ", "),
      call. = FALSE
    )
  }

  message(
    "[PLOT] Generating proportional Euler diagram for ",
    number_of_sets,
    " groups..."
  )

  # eulerr accepts a named list of sample spaces. Passing the complete
  # feature vectors lets the package derive every pairwise and higher-order
  # intersection automatically, including A&B&C and larger combinations.
  euler_fit <- tryCatch(
    eulerr::euler(
      group_feature_sets,
      shape = "ellipse"
    ),
    error = function(e) {
      stop(
        "Could not fit the multi-group Euler diagram: ",
        conditionMessage(e),
        call. = FALSE
      )
    }
  )

  euler_stress <- safe_metric(euler_fit, "stress")
  euler_diag_error <- safe_metric(euler_fit, "diagError")
  euler_max_region_error <- safe_max_metric(
    euler_fit,
    "regionError"
  )

  fit_warning <- if (
    is.finite(euler_diag_error) &&
    euler_diag_error > 0.05
  ) {
    paste0(
      " Warning: the diagnostic error is above 0.05; ",
      "interpret ellipse areas cautiously."
    )
  } else {
    ""
  }

  euler_caption <- paste0(
    "Euler diagram fitted from all pairwise and higher-order ",
    labels$singular,
    " intersections across ",
    number_of_sets,
    " groups. Stress: ",
    signif(euler_stress, 4),
    "; diagnostic error: ",
    signif(euler_diag_error, 4),
    "; maximum region error: ",
    signif(euler_max_region_error, 4),
    ". For three or more groups, an exact area-proportional ellipse ",
    "configuration may not exist; these fit statistics quantify the ",
    "approximation.",
    fit_warning,
    " Presence was defined as normalized abundance > ",
    format(
      opt$presence_threshold,
      scientific = FALSE,
      trim = TRUE
    ),
    " in at least one sample from the corresponding group."
  )

  save_euler_pdf(
    fit = euler_fit,
    output_file = euler_output_file,
    width = opt$width,
    height = opt$height,
    title = title_text,
    subtitle = subtitle_text,
    caption = euler_caption,
    label_type = opt$label_type,
    number_of_sets = number_of_sets
  )
}

output_stem <- sub("\\.pdf$", "", output_file, ignore.case = TRUE)

if (opt$write_summary) {
  summary_rows <- data.frame(
    metric = c(
      paste0("group:", groups),
      "shared_by_all_groups",
      "union"
    ),
    value = c(
      as.integer(group_counts[groups]),
      length(shared_all),
      length(union_features)
    ),
    samples = c(
      as.integer(group_sample_counts[groups]),
      NA_integer_,
      NA_integer_
    ),
    stringsAsFactors = FALSE
  )

  summary_file <- paste0(output_stem, "_summary.tsv")
  write.table(
    summary_rows,
    file = summary_file,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
  message("[OK] Summary generated: ", summary_file)
}

if (opt$write_lists) {
  for (group_name in groups) {
    group_file <- paste0(
      output_stem,
      "_",
      sanitize_filename(group_name),
      "_features.txt"
    )
    write_feature_list(group_feature_sets[[group_name]], group_file)
    message("[OK] Feature list generated: ", group_file)
  }

  shared_file <- paste0(output_stem, "_shared_by_all_features.txt")
  union_file <- paste0(output_stem, "_union_features.txt")

  write_feature_list(shared_all, shared_file)
  write_feature_list(union_features, union_file)

  message("[OK] Shared feature list generated: ", shared_file)
  message("[OK] Union feature list generated: ", union_file)
}

message("[DONE] Finished successfully.")
